### ISSUE TITLE
No releases - how to properly set up?

### ISSUE THREAD

**Issue by m3adow** [rugk/borg-cron-helper#14]
Hi all,  
first of all I want to say thanks for theses scripts. I've just recently found borg-cron-helper and am planning to build it into my borg container Therefore I want to automate the installation of borg-cron-helper. The Readme states to use releases and compare them against a PGP key. But there are no releases (yet?).

Are future releases planned or shall I just use git to get the repo?

Either way this is a bug report either for the missing of releases described in the README or for a wrong set up description in the README.

**Comment by rugk** [comment]
> Are future releases planned or shall I just use git to get the repo?

Yes, they are. However, I want to test the thing a bit more and maybe change the one thing or so.

For now you can use the git repo. BTW: You can verify this too as I sign my git commits. Just use [`git verify-commit`](https://git-scm.com/docs/git-verify-commit):
```sh
$ git verify-commit HEAD
gpg: Signature made Thu Sep 15 15:23:54 2016 CEST
gpg:                using RSA key 0x05D40A636AFAB34D
gpg: Good signature from "rugk git (software signing only) <rugk@posteo.de>" [<trust level here>]
Primary key fingerprint: ABA9 B8F6 F448 B07F D7EA  4A1A 05D4 0A63 6AFA B34D
```

**Comment by rugk** [comment]
I'll close this issue, if we have a working release.

**Comment by rugk** [comment]
done
