### ISSUE TITLE
Retry pruning

### ISSUE THREAD

**Issue by JimboJoe** [rugk/borg-cron-helper#45]
Hello,
I have an unreliable connection, and decided to use borg-cron-helper to get a reliable backup procedure. Thanks for that! 👍 
The problem is that my connection got disconnected during the pruning phase, and that phase isn't protected. Could it be protected with the same principles?

**Comment by rugk** [comment]
Sure, so I'd say we should retry it (independently from the main backup) for the same account of times (or do we need another counter for that?). Also the local lock system has to be used, of course.
