### ISSUE TITLE
zenity : Error showing notification

### ISSUE THREAD

**Issue by hubitor** [rugk/borg-cron-helper#48]
Backups seem to be working properly but I'm getting following error when using zenity :

Mar 20 00:15:06 myhost borgcron_starter.sh[9251]: [2018-03-20 00:15:06] Backup "test-backup" ended successfully.
Mar 20 00:15:06 myhost dbus-daemon[9298]: [session uid=1000 pid=9296] Activating service name='org.freedesktop.Notifications' requested by ':1.0' (uid=1000 pid=9291 comm="zenity --notification --window-icon /bin/borg-cron")
Mar 20 00:15:31 myhost zenity[9291]: **Error showing notification: Error calling StartServiceByName for org.freedesktop.Notifications: Timeout was reached**
Mar 20 00:15:34 myhost systemd[1]: Started BorgBackup.

I have replaced this line in borgcron.sh:
**zenity --notification --window-icon "$icon" --text "BorgBackup: $BACKUP_NAME**
with this one:
**kdialog --title "BorgBackup" --icon "$icon" --passivepopup "BorgBackup: $BACKUP_NAME**

just to see if it works with something else and now a notification appears. 

OS: Arch with KDE Plasma

**Comment by rugk** [comment]
If it works with kdialog, just use this. 😄  That's the whole reason why you can adjust it. (Also, maybe add it to the wiki...)

I am not even sure zenity works on KDE. Does it work when you manually call it in the console?

Or, if you still want to use zenity, maybe it is also a permission error. Did you follow https://github.com/rugk/borg-cron-helper/wiki/How-to-setup%3F#6-setup-notifications-optional?

**Comment by hubitor** [comment]
> If it works with kdialog, just use this. smile That's the whole reason why you can adjust it. (Also, maybe add it to the wiki...)

This was only a short test to check if it works with another program. It needs more work to make it work properly (e.g. the notification appears somewhere on one of my displays and it doesn't look so nice as when I call it manually).

>  I am not even sure zenity works on KDE. Does it work when you manually call it in the console?

I have read that zenity does not play well with KDE although it works when I call it manually.

> Or, if you still want to use zenity, maybe it is also a permission error. Did you follow https://github.com/rugk/borg-cron-helper/wiki/How-to-setup%3F#6-setup-notifications-optional?

Yes, I followed the wiki and it should work out of the box but it didn't! I use Xorg and I run borg and borg-cron-helper as a normal user. I did add DISPLAY=:0 variable to my borg script and it still didn't work. Then I did steps 1,2,4 and it still didn't work.

**Comment by rugk** [comment]
So you run borg as the same user, where the notification should be shown?
If so, you should not even have to use the steps from the wiki.

**Comment by hubitor** [comment]
> So you run borg as the same user, where the notification should be shown?
> If so, you should not even have to use the steps from the wiki.

Yes, but it didn't work...

**Comment by rugk** [comment]
That sounds very strange. If you can run it on the shell manually, it should also work automatically in the script.
Maybe the command line you try is is different or so?

Let me know if you find any solution.

**Comment by rugk** [comment]
> I have replaced this line in borgcron.sh:

BTW, usually you should not replace files in the main borgcron file. Instead override the functions in your config file.

**Comment by rugk** [comment]
Closing due to cleaning up old unresponsive issues.
