### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by rugk** [rugk/borg-cron-helper#5]
I am going to change the license from CC0 to [MIT license](https://choosealicense.com/licenses/mit/) for `borgcron.sh`. Naturally old code stays licensed under the old license, but any new addition afterwards is licensed under the new license.
All other scripts will stay CC0-licensed as they are really minimal.

Collecting contributor agreements here:
* [x] @kinafu

**Comment by kinafu** [comment]
I do agree 👍
