### ISSUE TITLE
Support excluding directories from backup

### ISSUE THREAD

**Issue by shankari** [rugk/borg-cron-helper#51]
I looked at the example parameters, and there is support for adding directories (`ADD_BACKUP_PARAMS`). However, there is no support for excluding directories from the backup. 

The default automating example on the borg backup page (https://borgbackup.readthedocs.io/en/1.1-maint/quickstart.html#automating-backups) adds `/var` and excludes `'/var/cache/*'` and `'/var/tmp/*'`, and I think I'd like to follow a similar pattern.

**Comment by shankari** [comment]
I'm happy to submit a PR if interested. I'm currently thinking of supporting a `EXCLUDE_OPTS` variable where any possible exclusion options (https://borgbackup.readthedocs.io/en/1.1-maint/usage/create.html#) can be specified.

**Comment by rugk** [comment]
So you could already use `ADD_BACKUP_PARAMS`, e.g.with `--exclude …` or, as I'd prefer it with a text file of exclusion?

And not everybody will use exclusions, anyway…

**Comment by shankari** [comment]
@rugk good point that I could use `ADD_BACKUP_PARAMS` - I guess when I see `ADD_BACKUP_PARAMS`, I am thinking of backup params for adding new locations.

So your suggestion is to make a doc fix by changing the sample?

I already made the exclude changes in my fork, but I can do this instead.

**Comment by shankari** [comment]
do you want me to submit a doc fix for changing the sample? If not, feel free to close this issue.

**Comment by rugk** [comment]
Okay, so the real issue you had was that you misinterpreted what the `ADD_BACKUP_PARAMS` does?

So yeah, feel free to:
* rename this variable to make it clearer (would `ADD_BACKUP_PARAMETERS` already work? Just consider backwards-compatibility, i.e. old config shall still work after the update.
* maybe adjust the comment on that line?
* as you said, feel free to add an "exclude example", yes.
