### ISSUE TITLE
`borg.timer` needs to be both enabled and started with systemctl

### ISSUE THREAD

**Issue by shankari** [rugk/borg-cron-helper#52]
I followed the instructions to enable automatic backups, however, the timer was listed as inactive.

```
# systemctl list-timers --all
NEXT                         LEFT          LAST                         PASSED     UNIT
Sun 2018-12-30 13:03:36 PST  5min left     Sun 2018-12-30 12:04:22 PST  53min ago  anacr
Sun 2018-12-30 14:13:44 PST  1h 16min left Sun 2018-12-30 05:43:41 PST  7h ago     certb
Sun 2018-12-30 15:15:13 PST  2h 17min left Sun 2018-12-30 02:21:41 PST  10h ago    motd-
Sun 2018-12-30 16:05:45 PST  3h 8min left  Sun 2018-12-30 05:22:09 PST  7h ago     apt-d
Mon 2018-12-31 00:00:00 PST  11h left      Mon 2018-12-24 00:00:40 PST  6 days ago fstri
Mon 2018-12-31 06:08:26 PST  17h left      Sun 2018-12-30 06:29:34 PST  6h ago     apt-d
Mon 2018-12-31 12:12:08 PST  23h left      Sun 2018-12-30 12:12:08 PST  45min ago  syste
n/a                          n/a           n/a                          n/a        borg.
n/a                          n/a           Thu 2018-12-27 11:58:12 PST  3 days ago uread
```

I poked around on the internet and found https://www.certdepot.net/rhel7-use-systemd-timers/
So I started the timer as well, and then it showed as active.

```
# systemctl start borg.timer
# systemctl list-timers --all
NEXT                         LEFT          LAST                         PASSED     UNIT
Sun 2018-12-30 13:03:36 PST  4s left       Sun 2018-12-30 12:04:22 PST  59min ago  anacr
Sun 2018-12-30 14:13:44 PST  1h 10min left Sun 2018-12-30 05:43:41 PST  7h ago     certb
Sun 2018-12-30 15:15:13 PST  2h 11min left Sun 2018-12-30 02:21:41 PST  10h ago    motd-
Sun 2018-12-30 16:05:45 PST  3h 2min left  Sun 2018-12-30 05:22:09 PST  7h ago     apt-d
Mon 2018-12-31 00:00:00 PST  10h left      Mon 2018-12-24 00:00:40 PST  6 days ago fstri
Mon 2018-12-31 00:55:39 PST  11h left      n/a                          n/a        borg.
Mon 2018-12-31 06:08:26 PST  17h left      Sun 2018-12-30 06:29:34 PST  6h ago     apt-d
Mon 2018-12-31 12:12:08 PST  23h left      Sun 2018-12-30 12:12:08 PST  51min ago  syste
n/a                          n/a           Thu 2018-12-27 11:58:12 PST  3 days ago uread
```
The wiki needs to be updated to include `$ systemctl start borg.timer` in addition to `systemctl enable borg.timer`

**Comment by shankari** [comment]
@rugk I am happy to make the change if you like; I am not sure how much control you want over the project.

**Comment by rugk** [comment]
So you are saying you need to start the timer once (even after getting enabled), before it runs? 

If this is really the case, then yes, feel free to adjust the wiki. However, IMHO that behavior makes no sense at all for systemd and I did not test it right now, but the blog you linked also does not explicitly state that this `systemctl start` was really required?

So I'd really prefer a better source for that. I mean, are you sure this was really the thing that was causing/fixing the issue?

**Comment by shankari** [comment]
> So you are saying you need to start the timer once (even after getting enabled), before it runs?

Yes, at least on ubuntu 18.04.

> but the blog you linked also does not explicitly state that this systemctl start was really required?

Are you sure? The first line under "Execution" is

> Activate at boot and start the backup timer to get your website backed up every day:

Note the "and start" and the **lack of** any "Optional"

If you want other sources, https://wiki.archlinux.org/index.php/Systemd/Timers says, under "Management" (emphasis mine)

> To use a timer unit enable and **start** it like any other unit (remember to add the .timer suffix). To view all started timers, run: 

And yes, if I stop it, it disappears from the list of active timers and returns only when I start it (see below).

```
# systemctl list-timers | grep borg
Tue 2019-01-01 01:41:45 PST  18h left      Mon 2018-12-31 01:04:38 PST  5h 57min ago borg.timer                   borg.service
# systemctl stop borg.timer
# systemctl list-timers | grep borg
# systemctl start borg.timer
# systemctl list-timers | grep borg
Tue 2019-01-01 00:13:35 PST  17h left      Mon 2018-12-31 01:04:38 PST  5h 57min ago borg.timer                   borg.service
```

**Comment by shankari** [comment]
Fixed in https://github.com/rugk/borg-cron-helper/wiki/How-to-setup%3F/be2916db7f19ee52bef503f3623a387b721dee8f

**Comment by rugk** [comment]
Ah, I thought that `start` would trigger the command immediately, but it seems it only "triggers" the timer, i.e. enables it.

I can imagine, however, that instead of starting it manually a restart of the server would also work, as the `enable` command does "[e]nable a unit to be started on bootup" ([acc. to Arch wiki](https://wiki.archlinux.org/index.php/Systemd#Using_units)).
(Maybe that is why I did not notice it.)

Anyway, thanks for fixing this in the wiki. :smile:
