### ISSUE TITLE
Error on borgcron_starter.sh execution

### ISSUE THREAD

**Issue by daPhipz** [rugk/borg-cron-helper#55]
I cloned the git repo on my local machine.
I edited the example backup script to fit my needs and renamed it to `home-backup.sh`.
Then, I followed your guide on [how to set up](https://github.com/rugk/borg-cron-helper/wiki/How-to-setup%3F), finally, I executed `borgcron_starter.sh` manually to check if everything works.
This is the output:
```
[2019-01-15 00:40:23] Backup home started with borg 1.1.8, helper PID: 5490.
usage: borg create [-h] [--critical] [--error] [--warning] [--info] [--debug]
                   [--debug-topic TOPIC] [-p] [--log-json]
                   [--lock-wait SECONDS] [--show-version] [--show-rc]
                   [--umask M] [--remote-path PATH] [--remote-ratelimit RATE]
                   [--consider-part-files] [--debug-profile FILE] [-n | -s]
                   [--list] [--filter STATUSCHARS] [--json] [--no-cache-sync]
                   [--no-files-cache] [--stdin-name NAME] [-e PATTERN]
                   [--exclude-from EXCLUDEFILE] [--pattern PATTERN]
                   [--patterns-from PATTERNFILE] [--exclude-caches]
                   [--exclude-if-present NAME] [--keep-exclude-tags]
                   [--exclude-nodump] [-x] [--numeric-owner] [--noatime]
                   [--noctime] [--nobirthtime] [--nobsdflags] [--ignore-inode]
                   [--files-cache MODE] [--read-special] [--comment COMMENT]
                   [--timestamp TIMESTAMP] [-c SECONDS]
                   [--chunker-params PARAMS] [-C COMPRESSION]
                   ARCHIVE [PATH [PATH ...]]
borg create: error: argument ARCHIVE: "/home/philipp/..": No archive specified
[2019-01-15 00:40:24] Borg exited with fatal error.
[2019-01-15 00:40:24] Wait 5m…

# I pressed Ctrl+C here, for obvious reasons
^C[2019-01-15 00:40:26] Backup home (PID: 5490) interrupted by INT.
[2019-01-15 00:40:26] Showing zenity (notification) to philipp (id=1000).
/usr/bin/sudo

** (zenity:5536): WARNING **: 00:40:26.581: Error showing notification: Verbindung ist gescheitert: Datei oder Verzeichnis nicht gefunden
```
How is this `borg create` error possible? I didn't touch the borg command at all - the only place where I changed `borgcron.sh` is [here](https://github.com/daPhipz/borg-cron-helper/commit/19c7b4cc03b9ebdc8906db4d083d2beb07cf8507).
See the [personal-changes branch](https://github.com/daPhipz/borg-cron-helper/tree/personal-changes) in my fork for all changes I made.

Can you spot my mistake?

**Comment by rugk** [comment]
I've had a quick look and saw no obvious error. You can try to add an [echo here](https://github.com/daPhipz/borg-cron-helper/blob/3b5eea49dbb118855d53569f8e1a138680081650/borgcron.sh#L375) to log the command line the script runs. Maybe this can help to debug the problem?

**Comment by daPhipz** [comment]
Hmmm... I haven't really found the cause of the problem, but a workaround:
The flag `--exclude /home/philipp/.*` got expanded to all directories that are affected by it, like this:

```
--exclude /home/philipp/. /home/philipp/.. /home/philipp/.Xauthority
          /home/philipp/.atom /home/philipp/.backup /home/philipp/.bash_history
          /home/philipp/.bash_logout /home/philipp/.bashrc /home/philipp/.cache
          /home/philipp/.config /home/philipp/.dbus /home/philipp/.dropbox
          /home/philipp/.dropbox-dist /home/philipp/.face /home/philipp/.face.icon
          /home/philipp/.gconf /home/philipp/.gitconfig /home/philipp/.gnupg
          /home/philipp/.gtkrc-2.0 /home/philipp/.java /home/philipp/.kde
          /home/philipp/.local /home/philipp/.mozilla /home/philipp/.pki
          /home/philipp/.profile /home/philipp/.pulse-cookie
          /home/philipp/.selected_editor /home/philipp/.ssh /home/philipp/.steam
          /home/philipp/.steampath /home/philipp/.steampid
          /home/philipp/.sudo_as_admin_successful /home/philipp/.wget-hsts
          /home/philipp/.xmind /home/philipp/.xsession-errors
```
My guess is, that `/home/philipp/..` is not a valid directory and thus, borg stops with an error.
My workaround: put the exact same exclude expression in an exclude file, and everything works as expected. Strange...

However, I wasn't able to set up notifications following your guide on the wiki. No big deal though, I will just check if everything works manually from time to time ;)

**Comment by rugk** [comment]
Ah, no, the solution is obvious when I know your problem analysis now. Actually, you found the problem and you just need to prevent the shell from expanding it:
```diff
-ADD_BACKUP_PARAMS="--checkpoint-interval=120 --exclude-caches --exclude /home/philipp/tmp/* --exclude /home/philipp/.* --exclude /home/philipp/snap --exclude-from /home/philipp/bin/borg-helper/config/exclude.txt" # additional parameters to pass to borg create
+ADD_BACKUP_PARAMS="--checkpoint-interval=120 --exclude-caches --exclude '/home/philipp/tmp/*' --exclude '/home/philipp/.*' --exclude /home/philipp/snap --exclude-from /home/philipp/bin/borg-helper/config/exclude.txt" # additional parameters to pass to borg create
```

You need to quote the strings. Actually, this would also have been the case, if you would have run borg manually on the command line with the same arguments. (So it is not a problem/issue of these cron scripts, here.)

**Comment by rugk** [comment]
BTW this is a common shell scripting mistake, see https://github.com/koalaman/shellcheck/wiki/Sc2086.
Unfortunately shellcheck is not able to detect your issue there, as it is actually quoted as I need to pass these arguments to borg itself. And only there, they get "unquoted".

**Comment by daPhipz** [comment]
Ah I see - thanks for the assistance, though! Appreciate it :)
