### ISSUE TITLE
Ability to invoke databasedump.sh with parameters

### ISSUE THREAD

**Issue by kinafu** [rugk/borg-cron-helper#60]
Right now it's possible, to write username and password of the db-user into the [mysql backup script ](https://github.com/kinafu/borg-cron-helper/blob/master/tools/databasedump.sh)directly.
The ability to have this kind of interface
`$ ./databasedump.sh backup password /root/backup/db`
additionally to
```
USER="backup"
PASSWORD="password"
DIR="/root/backup/db"
```
would help in avoiding redundancy and facilitate maintainability.

Right now the easiest way is to create copies of `databasedump.sh` with "hard-coded" credentials.
If one needs to make a change in the code executing the backup, he would need to update all of his copies.

**Comment by rugk** [comment]
Okay, so the use case are multiple backups? That's indeed a nice idea.

So feel free to make a PR. :smiley: 
Just make the parameters optional, so it still falls back to the old hardcoded ones, if nothing is passed.

**Comment by rugk** [comment]
@kinafu Does upvoting mean you take this on? (Assuming this, I'll assign you here.)

**Comment by rugk** [comment]
@kinafu If you need any pointers/help or have questions, feel free to ask.
