### ISSUE TITLE
Disable desktop notifications in terminal-only mode

### ISSUE THREAD

**Issue by kinafu** [rugk/borg-cron-helper#72]
Right now, borgcronhelper attempts to show notifications or at least tries to do sth. like that by default.
I use borgcronhelper on a headless server and can get notified _only_ by cron/chronic.

With the default setting, the backup report always contains the error:
`(zenity:29707): Gtk-WARNING **: cannot open display: `

My proposal:
In each backup config we need a variable to drop desktop notifications.
Right now, you can change [borgcron.sh](https://github.com/rugk/borg-cron-helper/blob/master/borgcron.sh#L262) to deactivate the feature. But changes to borgcron.sh would become overwritten by updates to borg-cron-helper.

**Comment by rugk** [comment]
The function `guiCanShowNotifications` should check whether you have zenity installed and if not not try to show notifications AFAIK on server systems (without a desktop) zenity should not be installed, should it?

AFAIK overwriting that function `guiCanShowNotifications() { return 1 }` should disable the feature anyway…

**Comment by kinafu** [comment]
I have also installed a desktop env. on my server, so zenity is installed by default, too.

To get the current session manager, we might use the systemd login manager.
`loginctl show-session $XDG_SESSION_ID -p Type`
I've tested the command successfully on three different devices using a terminal session, wayland and x-server. 
Comand returns `Type=tty` for terminal-only sessions,
`Type=wayland` or `Type=x11` for the corresponding desktop managers..

**Comment by rugk** [comment]
> I have also installed a desktop env. on my server, so zenity is installed by default, too.

Then I'd argue showing notifications makes sense… 

> To get the current session manager, we might use the systemd login manager.

Yeah, I guess something like this is implemented in the zenityProxy (needs to be enabled manually).

Here is where the magic happens:
https://github.com/rugk/borg-cron-helper/blob/master/tools/zenityProxy.sh

Feel free to test or adjust that, if it does not work…

**Comment by rugk** [comment]
Sorry, no, reading up again I had to revert https://github.com/rugk/borg-cron-helper/pull/73, because if you e.g. run the backup as `root` there will never be a `$DISPLAY` set…

Or wait, actually it is set in my case:
```
$ sudo env|grep DISPLAY
DISPLAY=:0
```

Likely, because the system starts as _root_ and then switches to gdm (in case of GNOME) individual users… 

---

So all back again, I don't revert it. But we should keep this in mind, as it is a potential source for problems, when you e.g. run your backup under a special user that is just a CLI user (but should show notifications to a different user).

**Comment by rugk** [comment]
[Updated the wiki now](https://github.com/rugk/borg-cron-helper/wiki/How-to-setup%3F/_compare/a8093d0eeadae2c558a3448cf45e7aa502c5648e...0291b935edc20bbfed3c034088a26ce837c9da5e) to explain the changes and possible problems, if anyone tries to use that system under very special conditions (CLI-only user trying to show things to GUI-users, where CLI-only user is not root).
